function cclick() {
    let input = document.querySelector("input").value;
    var a = input.replace(/fuck/g, "frick")
    var c = a.replace(/Fuck/g, "Frick")
    var i = c.replace(/FUCK/g, "FRICK")
    var b = i.replace(/Shit/g, "Poop")
    var e = b.replace(/shit/g, "poop")
    var k = e.replace(/SHIT/g, "POOP")
    var t = k.replace(/bitch/g, "butt")
    var q = t.replace(/Bitch/g, "Butt")
    var u = q.replace(/BITCH/g, "BUTT")
    var o = u.replace(/dick/g, "jerk")
    var x = o.replace(/Dick/g, "Jerk")
    var y = x.replace(/DICK/g, "JERK")
    var v = y.replace(/damn/g, "dang")
    var g = v.replace(/Damn/g, "Dang")
    var p = g.replace(/DAMN/g, "DANG")
    var pp = p.replace(/Nigger/g, "Nipple")
    var ppp = pp.replace(/NIGGER/g, "NIPPLE")
    var pppp = ppp.replace(/nigger/g, "nipple")
    var ppppp = pppp.replace(/nigga/g, "nerd")
    var gg = ppppp.replace(/Nigga/g, "Nerd")
    var ttr = gg.replace(/NIGGA/g, "NERD")
    var why = ttr.replace(/cunt/g, "vagina")
    var why2 = why.replace(/Cunt/g, "Vagina")
    var why3 = why2.replace(/CUNT/g, "VAGINA")
    var why4 = why3.replace(/Cock/g, "Penis")
    var why5 = why4.replace(/cock/g, "penis")
    var why6 = why5.replace(/COCK/g, "PENIS")
    var why7 = why6.replace(/ass/g, "arse")
    var why8 = why7.replace(/Ass/g, "Arse")
    var why9 = why8.replace(/ASS/g, "ARSE")
    document.querySelector("span").textContent = why9;
}
//note: no feelings were hurt within the making of this
//and if a word is vulgar in any part of the word it was added